ALTER TABLE driver_profiles
  ADD COLUMN IF NOT EXISTS nombre VARCHAR(100),
  ADD COLUMN IF NOT EXISTS apellido VARCHAR(100),
  ADD COLUMN IF NOT EXISTS curso_puerto BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS notas TEXT;
